using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace LanguageData
{
    [System.Serializable]
    public class LanguageInfo
    {
        public int index; 
        public string KoreanWord;
        public string ChineseWord;
    }

    public static class WordPair
    {
        public static List<LanguageInfo> wordPairs = new List<LanguageInfo>
        {
        new LanguageInfo {KoreanWord = "아줌마",ChineseWord = "阿姨" },
        new LanguageInfo {KoreanWord = "문장의 끝에 쓰여 감탄·찬탄 따위 등의 어기를 나타냄", ChineseWord = "啊" },
        new LanguageInfo{KoreanWord= "(키가)작다",ChineseWord ="矮"  },
        new LanguageInfo{KoreanWord="취미",ChineseWord = "爱好"  },
        new LanguageInfo{KoreanWord="조용하다",ChineseWord="安静"},
        new LanguageInfo{KoreanWord="을,를(목적어를 동사 앞에 놓을 때 쓰는 것)",ChineseWord = "把"},
        new LanguageInfo{KoreanWord="(학급의)반",ChineseWord = "班"},
        new LanguageInfo{KoreanWord="옮기다",ChineseWord = "搬"},
        new LanguageInfo{KoreanWord="방법",ChineseWord ="办法" },
        new LanguageInfo{KoreanWord="사무실",ChineseWord ="办公室"},
        new LanguageInfo{KoreanWord="반",ChineseWord ="半" },
        new LanguageInfo {KoreanWord="도와주다",ChineseWord ="帮忙"  },
        new LanguageInfo{KoreanWord="가방",ChineseWord ="包"  },
        new LanguageInfo{KoreanWord="배부르다",ChineseWord ="饱"  },
        new LanguageInfo{KoreanWord="북쪽",ChineseWord ="北方"},
        new LanguageInfo{KoreanWord="~에게 당하다(피동을 나타냄)", ChineseWord ="被" },
        new LanguageInfo{KoreanWord="코", ChineseWord ="鼻子" },
        new LanguageInfo{KoreanWord="비교하다", ChineseWord ="比较" },
        new LanguageInfo{KoreanWord= "경기",ChineseWord ="比赛" },
        new LanguageInfo{KoreanWord="노트북", ChineseWord ="笔记本" },
        new LanguageInfo{KoreanWord="반드시,꼭",ChineseWord ="必须"},
        new LanguageInfo{KoreanWord="변화",ChineseWord ="变化" },
        new LanguageInfo{KoreanWord="다른 사람",ChineseWord ="别人" },
        new LanguageInfo{KoreanWord="냉장고", ChineseWord ="冰箱" },
        new LanguageInfo{KoreanWord="A뿐만 아니라 B도", ChineseWord ="不但A而且B" },
        new LanguageInfo{KoreanWord="메뉴판", ChineseWord ="菜单" },
        new LanguageInfo{KoreanWord="참가하다",ChineseWord = "参加" },
        new LanguageInfo{KoreanWord="풀",ChineseWord = "草" },
        new LanguageInfo{KoreanWord="층",ChineseWord = "层" },
        new LanguageInfo{KoreanWord="모자라다, 표준에 못 미치다",ChineseWord = "差" },
        new LanguageInfo{KoreanWord="슈퍼", ChineseWord ="超市" },
        new LanguageInfo{KoreanWord="셔츠",ChineseWord = "衬衫" },
        new LanguageInfo{KoreanWord="성적", ChineseWord ="成绩" },
        new LanguageInfo{KoreanWord="도시", ChineseWord ="城市" },
        new LanguageInfo{KoreanWord="지각하다", ChineseWord ="迟到" },
        new LanguageInfo{KoreanWord="-를 제외하고",ChineseWord = "除了" },
        new LanguageInfo{KoreanWord="배", ChineseWord ="船" },
        new LanguageInfo{KoreanWord="봄", ChineseWord ="春" },
        new LanguageInfo{KoreanWord="사전", ChineseWord ="词典" },
        new LanguageInfo{KoreanWord="똑똑하다,총명하다", ChineseWord = "聪明" },
        new LanguageInfo{KoreanWord="청소하다", ChineseWord = "打扫" },
        new LanguageInfo{KoreanWord="~하려고 하다", ChineseWord = "打算" },
        new LanguageInfo{KoreanWord="가지다,지니다",ChineseWord =  "带" },
        new LanguageInfo{KoreanWord="걱정하다", ChineseWord ="担心" },
        new LanguageInfo{KoreanWord="케이크",ChineseWord = "蛋糕" },
        new LanguageInfo{KoreanWord="당연히",ChineseWord = "当然" },
        new LanguageInfo{KoreanWord="-하게(부사를 나타낼 때 쓰임)",ChineseWord ="地"},
        new LanguageInfo{KoreanWord= "등",ChineseWord ="灯" },
        new LanguageInfo{KoreanWord="곳", ChineseWord ="地方" },
        new LanguageInfo{KoreanWord="지하철", ChineseWord ="地铁" },
        new LanguageInfo{KoreanWord="지도", ChineseWord ="地图" },
        new LanguageInfo{KoreanWord="엘리베이터", ChineseWord ="电梯" },
        new LanguageInfo {KoreanWord="이메일",ChineseWord = "电子邮件" },
        new LanguageInfo{KoreanWord="동쪽",ChineseWord = "东" },
        new LanguageInfo{KoreanWord="겨울 ",ChineseWord ="冬" },
        new LanguageInfo{KoreanWord="동물", ChineseWord ="动物" },
        new LanguageInfo{KoreanWord="짧다", ChineseWord ="短" },
        new LanguageInfo {KoreanWord="단련하다", ChineseWord ="锻炼" },
        new LanguageInfo{KoreanWord="얼마나", ChineseWord ="多么" },
        new LanguageInfo{KoreanWord="배고프다", ChineseWord ="饿" },
        new LanguageInfo{KoreanWord="귀", ChineseWord ="耳朵" },
        new LanguageInfo{KoreanWord="보내다,전송하다", ChineseWord ="发" },
        new LanguageInfo{KoreanWord="열나다", ChineseWord ="发烧" },
        new LanguageInfo{KoreanWord="발견하다", ChineseWord ="发现" },
        new LanguageInfo{KoreanWord="편리하다", ChineseWord ="方便" },
        new LanguageInfo{KoreanWord="놓다", ChineseWord ="放" },
        new LanguageInfo{KoreanWord="안심하다",ChineseWord = "放心" },
        new LanguageInfo{KoreanWord="(시간)분", ChineseWord ="分" },
        new LanguageInfo{KoreanWord="근처의", ChineseWord ="附近" },
        new LanguageInfo{KoreanWord="복습하다",ChineseWord = "复习" },
        new LanguageInfo{KoreanWord="깨끗하다",ChineseWord = "干净" },
        new LanguageInfo{KoreanWord="감기에 걸리다", ChineseWord ="感冒" },
        new LanguageInfo{KoreanWord="흥미가 있다",ChineseWord = "感兴趣" },
        new LanguageInfo{KoreanWord="방금",ChineseWord = "刚才" },
        new LanguageInfo{KoreanWord="키", ChineseWord ="个子" },
        new LanguageInfo{KoreanWord="에 근거하여", ChineseWord ="根据" },
        new LanguageInfo{KoreanWord="와,과", ChineseWord ="跟" },
        new LanguageInfo{KoreanWord="더욱,더", ChineseWord ="更" },
        new LanguageInfo{KoreanWord="kg(킬로그램)", ChineseWord ="公斤" },
        new LanguageInfo{KoreanWord="공원", ChineseWord ="公园" },
        new LanguageInfo{KoreanWord="이야기", ChineseWord ="故事" },
        new LanguageInfo{KoreanWord="바람이 불다", ChineseWord ="刮风" },
        new LanguageInfo{KoreanWord="닫다",ChineseWord ="关" },
        new LanguageInfo{KoreanWord="관계",ChineseWord = "关系" },
        new LanguageInfo{KoreanWord="관심", ChineseWord ="关心" },
        new LanguageInfo{KoreanWord="에 관하여", ChineseWord ="关于" },
        new LanguageInfo{KoreanWord="국가", ChineseWord ="国家" },
        new LanguageInfo{KoreanWord="건너다", ChineseWord ="过" },
        new LanguageInfo{KoreanWord="지나가다",ChineseWord = "过去" },
        new LanguageInfo{KoreanWord="아니면, 그래도",ChineseWord = "还是" },
        new LanguageInfo{KoreanWord="무섭다",ChineseWord = "害怕" },
        new LanguageInfo{KoreanWord="칠판", ChineseWord ="黑板" },
        new LanguageInfo{KoreanWord="후에, 이후에",ChineseWord = "后来" },
        new LanguageInfo{KoreanWord="여권", ChineseWord ="护照" },
        new LanguageInfo{KoreanWord="쓰다,사용하다", ChineseWord ="花" },
        new LanguageInfo{KoreanWord="꽃", ChineseWord ="花" },
        new LanguageInfo{KoreanWord="그리다", ChineseWord ="画" },
        new LanguageInfo{KoreanWord="나쁘다", ChineseWord ="坏" },
        new LanguageInfo{KoreanWord="환영하다",ChineseWord = "欢迎" },
        new LanguageInfo{KoreanWord="환경",ChineseWord = "环境" },
        new LanguageInfo{KoreanWord="바꾸다,변경하다", ChineseWord ="换" },
        new LanguageInfo{KoreanWord="황허", ChineseWord ="黄河" },
        new LanguageInfo{KoreanWord="대답하다", ChineseWord ="回答" },
        new LanguageInfo{KoreanWord="회의",ChineseWord ="会议" },
        new LanguageInfo{KoreanWord="혹은", ChineseWord ="或者" },
        new LanguageInfo{KoreanWord="거의",ChineseWord = "几乎" },
        new LanguageInfo{KoreanWord="기회", ChineseWord ="机会" },
        new LanguageInfo{KoreanWord="대단히,매우", ChineseWord ="极" },
        new LanguageInfo{KoreanWord="기억하다", ChineseWord ="记得" },
        new LanguageInfo{KoreanWord="계절", ChineseWord ="季节" },
        new LanguageInfo{KoreanWord="검사하다",ChineseWord = "检查" },
        new LanguageInfo{KoreanWord="간단하다",ChineseWord = "简单" },
        new LanguageInfo{KoreanWord="만나다",ChineseWord = "见面" },
        new LanguageInfo{KoreanWord="건강하다", ChineseWord ="健康" },
        new LanguageInfo{KoreanWord="말하다, 이야기하다", ChineseWord ="讲" },
        new LanguageInfo{KoreanWord="가르치다",ChineseWord = "教" },
        new LanguageInfo{KoreanWord="뿔,돈의 단위", ChineseWord ="角" },
        new LanguageInfo{KoreanWord="발",ChineseWord ="脚"},
        new LanguageInfo{KoreanWord="맞이하다,마중하다", ChineseWord ="接" },
        new LanguageInfo{KoreanWord="거리", ChineseWord ="街道" },
        new LanguageInfo{KoreanWord="명절", ChineseWord ="节日" },
        new LanguageInfo{KoreanWord="프로그램",ChineseWord = "节目"},
        new LanguageInfo{KoreanWord="결혼하다",ChineseWord = "结婚" },
        new LanguageInfo{KoreanWord="끝나다,완료하다",ChineseWord = "结束" },
        new LanguageInfo{KoreanWord="해결하다", ChineseWord ="解决" },
        new LanguageInfo{KoreanWord="빌리다", ChineseWord ="借" },
        new LanguageInfo{KoreanWord="이미", ChineseWord ="经常" },
        new LanguageInfo{KoreanWord="를 통하여", ChineseWord ="经过" },
        new LanguageInfo{KoreanWord="사장", ChineseWord ="经理" },
        new LanguageInfo{KoreanWord="오래다,(시간이)길다", ChineseWord ="久" },
        new LanguageInfo{KoreanWord="오래 되다,옛날의",ChineseWord ="旧" },
        new LanguageInfo{KoreanWord="문장",ChineseWord ="句子" },
        new LanguageInfo{KoreanWord="결정하다",ChineseWord="决定"},
        new LanguageInfo{KoreanWord="귀엽다",ChineseWord="可爱" },
        new LanguageInfo{KoreanWord="목마르다", ChineseWord="渴" },
        new LanguageInfo{KoreanWord="15분", ChineseWord="刻" },
        new LanguageInfo{KoreanWord="손님", ChineseWord="客人" },
        new LanguageInfo {KoreanWord="에어컨",ChineseWord= "空调" },
        new LanguageInfo{KoreanWord="입", ChineseWord="口" },
        new LanguageInfo{KoreanWord="울다", ChineseWord="哭" },
        new LanguageInfo{KoreanWord="바지", ChineseWord="裤子" },
        new LanguageInfo{KoreanWord="젓가락", ChineseWord="筷子" },
        new LanguageInfo{KoreanWord="푸르다",ChineseWord= "蓝" },
        new LanguageInfo{KoreanWord="늙다",ChineseWord= "老" },
        new LanguageInfo{KoreanWord="떠나다", ChineseWord="离开" },
        new LanguageInfo{KoreanWord="선물",ChineseWord= "礼物" },
        new LanguageInfo{KoreanWord="역사",ChineseWord= "历史" },
        new LanguageInfo{KoreanWord="얼굴", ChineseWord="脸" },
        new LanguageInfo{KoreanWord="연습, 연습하다",ChineseWord="练习" },
        new LanguageInfo{KoreanWord="대(차를 세는 양사)", ChineseWord="辆" },
        new LanguageInfo{KoreanWord="잡담하다",ChineseWord= "聊天儿" },
        new LanguageInfo{KoreanWord="이해하다",ChineseWord= "了解" },
        new LanguageInfo{KoreanWord="이웃",ChineseWord= "邻居" },
        new LanguageInfo{KoreanWord="유학하다",ChineseWord= "留学" },
        new LanguageInfo{KoreanWord="층", ChineseWord="楼" },
        new LanguageInfo{KoreanWord="녹색",ChineseWord= "绿" },
        new LanguageInfo{KoreanWord="말",ChineseWord= "马" },
        new LanguageInfo{KoreanWord="곧, 금방", ChineseWord="马上" },
        new LanguageInfo{KoreanWord="만족하다", ChineseWord="满意" },
        new LanguageInfo{KoreanWord="모자",ChineseWord= "帽子" },
        new LanguageInfo{KoreanWord="쌀",ChineseWord= "米" },
        new LanguageInfo{KoreanWord="빵",ChineseWord= "面包" },
        new LanguageInfo{KoreanWord="알다", ChineseWord="明白" },
        new LanguageInfo{KoreanWord="(손에)쥐다,가지다",ChineseWord= "拿" },
        new LanguageInfo{KoreanWord="할머니",ChineseWord= "奶奶" },
        new LanguageInfo{KoreanWord="남쪽", ChineseWord="南" },
        new LanguageInfo{KoreanWord="어렵다",ChineseWord= "难" },
        new LanguageInfo{KoreanWord="곤란하다",ChineseWord= "难过" },
        new LanguageInfo{KoreanWord="학년", ChineseWord="年级" },
        new LanguageInfo{KoreanWord="젊다", ChineseWord="年轻" },
        new LanguageInfo{KoreanWord="새", ChineseWord="鸟" },
        new LanguageInfo{KoreanWord="노력, 노력하다", ChineseWord="努力" },
        new LanguageInfo{KoreanWord="등산하다", ChineseWord="爬山" },
        new LanguageInfo{KoreanWord="뚱뚱하다", ChineseWord="胖" },
        new LanguageInfo{KoreanWord="구두", ChineseWord="皮鞋" },
        new LanguageInfo{KoreanWord="맥주",ChineseWord= "啤酒" },
        new LanguageInfo{KoreanWord="병", ChineseWord="瓶子" },
        new LanguageInfo{KoreanWord="사실은", ChineseWord="其实" },
        new LanguageInfo{KoreanWord="기타", ChineseWord="其他" },
        new LanguageInfo{KoreanWord="이상하다", ChineseWord="奇怪" },
        new LanguageInfo{KoreanWord="타다",ChineseWord="骑" },
        new LanguageInfo{KoreanWord="이륙하다",ChineseWord= "起飞" },
        new LanguageInfo{KoreanWord="일어나다",ChineseWord= "起来" },
        new LanguageInfo{KoreanWord="분명하다", ChineseWord="清楚" },
        new LanguageInfo{KoreanWord="휴가를 내다", ChineseWord="请假" },
        new LanguageInfo{KoreanWord="가을", ChineseWord="秋" },
        new LanguageInfo{KoreanWord="치마", ChineseWord="裙子" },
        new LanguageInfo{KoreanWord="그리고 나서",ChineseWord="然后" },
        new LanguageInfo{KoreanWord="친절하다, 열정적이다",ChineseWord= "热情" },
        new LanguageInfo{KoreanWord="여기다, 생각하다", ChineseWord="认为" },
        new LanguageInfo{KoreanWord="열심히", ChineseWord="认真" },
        new LanguageInfo{KoreanWord="쉽다", ChineseWord="容易" },
        new LanguageInfo{KoreanWord="만약", ChineseWord="如果" },
        new LanguageInfo{KoreanWord="우산", ChineseWord="伞" },
        new LanguageInfo{KoreanWord="인터넷을 하다", ChineseWord="上网" },
        new LanguageInfo{KoreanWord="화나다",ChineseWord="生气" },
        new LanguageInfo{KoreanWord="소리", ChineseWord="声音" },
        new LanguageInfo{KoreanWord="세계",ChineseWord="世界" },
        new LanguageInfo{KoreanWord="시험하다", ChineseWord="试" },
        new LanguageInfo{KoreanWord="마르다", ChineseWord="瘦" },
        new LanguageInfo{KoreanWord="아저씨", ChineseWord="叔叔" },
        new LanguageInfo{KoreanWord="편안하다",ChineseWord="舒服" },
        new LanguageInfo{KoreanWord="나무", ChineseWord="树" },
        new LanguageInfo{KoreanWord="수학", ChineseWord="数学" },
        new LanguageInfo{KoreanWord="이를 닦다", ChineseWord="刷牙" },
        new LanguageInfo{KoreanWord="쌍", ChineseWord="双" },
        new LanguageInfo{KoreanWord="수준", ChineseWord="水平" },
        new LanguageInfo{KoreanWord="기사", ChineseWord="司机" },
        new LanguageInfo{KoreanWord="태양", ChineseWord="太阳" },
        new LanguageInfo{KoreanWord="특별하다,특별히", ChineseWord="特别" },
        new LanguageInfo{KoreanWord="아프다", ChineseWord="疼" },
        new LanguageInfo{KoreanWord="향상시키다", ChineseWord="提高" },
        new LanguageInfo{KoreanWord="체육", ChineseWord="体育" },
        new LanguageInfo{KoreanWord="달다", ChineseWord="甜" },
        new LanguageInfo{KoreanWord="가늘고 긴 것을 세는 양사", ChineseWord="条" },
        new LanguageInfo{KoreanWord="동료", ChineseWord="同事" },
        new LanguageInfo{KoreanWord="동의하다", ChineseWord="同意" },
        new LanguageInfo{KoreanWord="머리카락", ChineseWord="头发" },
        new LanguageInfo{KoreanWord="갑자기", ChineseWord="突然" },
        new LanguageInfo{KoreanWord="도서관", ChineseWord="图书馆" },
        new LanguageInfo{KoreanWord="다리", ChineseWord="腿" },
        new LanguageInfo{KoreanWord="완성하다", ChineseWord="完成" },
        new LanguageInfo{KoreanWord="그릇", ChineseWord="碗" },
        new LanguageInfo{KoreanWord="만", ChineseWord="万" },
        new LanguageInfo{KoreanWord="잊다", ChineseWord="忘记" },
        new LanguageInfo{KoreanWord="-를 위해서", ChineseWord="为" },
        new LanguageInfo{KoreanWord="-를 위해서", ChineseWord="为了" },
        new LanguageInfo{KoreanWord="분", ChineseWord="位" },
        new LanguageInfo{KoreanWord="문화", ChineseWord="文化" },
        new LanguageInfo{KoreanWord="서쪽", ChineseWord="西" },
        new LanguageInfo{KoreanWord="화장실", ChineseWord="洗手间" },
        new LanguageInfo{KoreanWord="습관", ChineseWord="习惯" },
        new LanguageInfo{KoreanWord="샤워하다", ChineseWord="洗澡" },
        new LanguageInfo{KoreanWord="여름", ChineseWord="夏" },
        new LanguageInfo{KoreanWord="우선,먼저", ChineseWord="先" },
        new LanguageInfo{KoreanWord="믿다", ChineseWord="相信" },
        new LanguageInfo{KoreanWord="바나나", ChineseWord="香蕉" },
        new LanguageInfo{KoreanWord="-를 향해서", ChineseWord="向" },
        new LanguageInfo{KoreanWord="닮다,비슷하다", ChineseWord="像" },
        new LanguageInfo{KoreanWord="조심하다", ChineseWord="小心" },
        new LanguageInfo{KoreanWord="교장,대학교 총장", ChineseWord="校长" },
        new LanguageInfo{KoreanWord="뉴스", ChineseWord="新闻" },
        new LanguageInfo{KoreanWord="신선하다", ChineseWord="新鲜" },
        new LanguageInfo{KoreanWord="신용카드", ChineseWord="信用卡" },
        new LanguageInfo{KoreanWord="캐리어", ChineseWord="行李箱" },
        new LanguageInfo{KoreanWord="팬더", ChineseWord="熊猫" },
        new LanguageInfo{KoreanWord="필요하다", ChineseWord="需要" },
        new LanguageInfo{KoreanWord="선택하다", ChineseWord="选择" },
        new LanguageInfo{KoreanWord="요구하다", ChineseWord="要求" },
        new LanguageInfo{KoreanWord="할아버지", ChineseWord="爷爷" },
        new LanguageInfo{KoreanWord="일반적으로", ChineseWord="一般" },
        new LanguageInfo{KoreanWord="-하면서-하다,한 면", ChineseWord="一边" },
        new LanguageInfo{KoreanWord="꼭", ChineseWord="一定" },
        new LanguageInfo{KoreanWord="총,합계,모두", ChineseWord="一共" },
        new LanguageInfo{KoreanWord="잠시,곧,이따가", ChineseWord="一会儿" },
        new LanguageInfo{KoreanWord="같다", ChineseWord="一样" },
        new LanguageInfo{KoreanWord="줄곧,계속", ChineseWord="一直" },
        new LanguageInfo{KoreanWord="이전,예전", ChineseWord="以前" },
        new LanguageInfo{KoreanWord="음악", ChineseWord="音乐" },
        new LanguageInfo{KoreanWord="은행", ChineseWord="银行" },
        new LanguageInfo{KoreanWord="음료수", ChineseWord="饮料" },
        new LanguageInfo{KoreanWord="-해야한다,마땅하다", ChineseWord="应该" },
        new LanguageInfo{KoreanWord="영향,영향을 주다", ChineseWord="影响" },
        new LanguageInfo{KoreanWord="사용하다,이용하다,~로", ChineseWord="用" },
        new LanguageInfo{KoreanWord="놀이,게임", ChineseWord="游戏" },
        new LanguageInfo{KoreanWord="유명하다", ChineseWord="有名" },
        new LanguageInfo{KoreanWord="또", ChineseWord="又" },
        new LanguageInfo{KoreanWord="(우연히)만나다", ChineseWord="遇到" },
        new LanguageInfo{KoreanWord="돈의 단위,위안", ChineseWord="元" },
        new LanguageInfo{KoreanWord="원하다,바라다", ChineseWord="愿意" },
        new LanguageInfo{KoreanWord="달", ChineseWord="月亮" },
        new LanguageInfo{KoreanWord="넘다,-할수록", ChineseWord="越" },
        new LanguageInfo{KoreanWord="일어서다,역,정거장", ChineseWord="站" },
        new LanguageInfo{KoreanWord="장,종이세는 양사", ChineseWord="张" },
        new LanguageInfo{KoreanWord="자라다", ChineseWord="长" },
        new LanguageInfo{KoreanWord="조급해하다", ChineseWord="着急" },
        new LanguageInfo{KoreanWord="고려하다,돌보다", ChineseWord="照顾" },
        new LanguageInfo{KoreanWord="사진", ChineseWord="照片" },
        new LanguageInfo{KoreanWord="사진기", ChineseWord="照相机" },
        new LanguageInfo{KoreanWord="마리", ChineseWord="只" },
        new LanguageInfo{KoreanWord="단지", ChineseWord="只" },
        new LanguageInfo{KoreanWord="-해야지만 비로소-", ChineseWord="只有~才~" },
        new LanguageInfo{KoreanWord="가운데", ChineseWord="中间" },
        new LanguageInfo{KoreanWord="중국어", ChineseWord="中文" },
        new LanguageInfo{KoreanWord="드디어,결국", ChineseWord="终于" },
        new LanguageInfo{KoreanWord="종류(양사)", ChineseWord="种" },
        new LanguageInfo{KoreanWord="중요하다", ChineseWord="重要" },
        new LanguageInfo{KoreanWord="주말", ChineseWord="周末" },
        new LanguageInfo{KoreanWord="주요한", ChineseWord="主要" },
        new LanguageInfo{KoreanWord="집중하다", ChineseWord="注意" },
        new LanguageInfo{KoreanWord="자기", ChineseWord="自己" },
        new LanguageInfo{KoreanWord="자전거", ChineseWord="自行车" },
        new LanguageInfo{KoreanWord="항상,늘", ChineseWord="总是" },
        new LanguageInfo{KoreanWord="입", ChineseWord="嘴" },
        new LanguageInfo{KoreanWord="최후,마지막", ChineseWord="最后" },
        new LanguageInfo{KoreanWord="최근,요즈음", ChineseWord="最近" },
        new LanguageInfo{KoreanWord="숙제", ChineseWord="作业" },
        };
    }
}